### ISSUE TITLE
[BUG] +2/3 committed an invalid block: wrong Block.Header.AppHash.  Expected XXX, got YYY

### ISSUE THREAD

**Issue by nyxynyx** [terra-money/classic-core#774]
**Describe the bug**
Trying to bootstrap a `bombay-12` testnet node using a [`bombay-12-pruned` `2022-05-19 14:56:43` quicksync snapshot](https://dl2.quicksync.io/bombay-12-pruned.20220519.0510.tar.lz4), but when it just starts, the node crashes with this error:

```
11:07AM INF Replay: BlockPart height=9064570 module=consensus peer=344199da2be16adc58e7c7cf85607ee6d65f1eb4 round=0
11:07AM INF Replay: BlockPart height=9064570 module=consensus peer=05bf2a0786c34f07452f21a0d4fc00061224b59f round=0
11:07AM INF Replay: BlockPart height=9064571 module=consensus peer=c7c9c028a030ccaa61ab1c935a787864e528b8b0 round=0
11:07AM INF received complete proposal block hash=7CCE36382A2204F1DD105A3038718AE3399301509CC18A7DAA3165E60721F72A height=9064571 module=consensus
panic: +2/3 committed an invalid block: wrong Block.Header.AppHash.  Expected 5C219B627AE08E9CEE0203F466A14BD13A4F1090AC2CD0F130FF608F64FD8E6C, got EBFEAA55BB72B19227373DDC50AD368D2B25A0173F76993385E6FB80F5119114

goroutine 74 [running]:
github.com/tendermint/tendermint/consensus.(*State).finalizeCommit(0xc0013c5500, 0x8a507b)
    github.com/tendermint/tendermint@v0.34.14/consensus/state.go:1575 +0x1005
github.com/tendermint/tendermint/consensus.(*State).tryFinalizeCommit(0xc0013c5500, 0x8a507b)
    github.com/tendermint/tendermint@v0.34.14/consensus/state.go:1546 +0x305
github.com/tendermint/tendermint/consensus.(*State).addProposalBlockPart(0xc0013c5500, 0x0?, {0xc00f393290?, 0xc0006b0800?})
    github.com/tendermint/tendermint@v0.34.14/consensus/state.go:1919 +0x92e
github.com/tendermint/tendermint/consensus.(*State).handleMsg(0xc0013c5500, {{0x23a83e0?, 0xc00f3acf78?}, {0xc00f393290?, 0xc00308f158?}})
    github.com/tendermint/tendermint@v0.34.14/consensus/state.go:820 +0x16d
github.com/tendermint/tendermint/consensus.(*State).readReplayMessage(0xc0013c5500, 0x1c972d6?, {0x0?, 0x0?})
    github.com/tendermint/tendermint@v0.34.14/consensus/replay.go:81 +0x87f
github.com/tendermint/tendermint/consensus.(*State).catchupReplay(0xc0013c5500, 0x8a507b)
    github.com/tendermint/tendermint@v0.34.14/consensus/replay.go:160 +0x72f
github.com/tendermint/tendermint/consensus.(*State).OnStart(0xc0013c5500)
    github.com/tendermint/tendermint@v0.34.14/consensus/state.go:314 +0x19a
github.com/tendermint/tendermint/libs/service.(*BaseService).Start(0xc0013c5500)
    github.com/tendermint/tendermint@v0.34.14/libs/service/service.go:140 +0x243
github.com/tendermint/tendermint/consensus.(*Reactor).SwitchToConsensus(_, {{{0xb, 0x0}, {0xc000463720, 0x7}}, {0xc000463727, 0x9}, 0x5a06e1, 0x8a507a, {{0xc00010fb00, ...}, ...}, ...}, ...)
    github.com/tendermint/tendermint@v0.34.14/consensus/reactor.go:127 +0x191
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc000441c00, 0x0)
    github.com/tendermint/tendermint@v0.34.14/blockchain/v0/reactor.go:328 +0x10dd
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
    github.com/tendermint/tendermint@v0.34.14/blockchain/v0/reactor.go:110 +0x7a
```

There's no problems syncing the node from scratch after syncing 150,000 blocks.

**To Reproduce**

```
git clone https://github.com/terra-money/classic-core
cd classic-core
git checkout v0.5.9
make install
terrad init terratest --chain-id bombay-12
wget https://raw.githubusercontent.com/terra-money/classic-testnet/master/bombay-12/genesis.json
cp genesis.json ~/.terra/config/genesis.json
sed -i 's/minimum-gas-prices = "0uluna"/minimum-gas-prices = "0.01133uluna,0.15uusd,0.104938usdr,169.77ukrw,428.571umnt,0.125ueur,0.98ucny,16.37ujpy,0.11ugbp,10.88uinr,0.19ucad,0.14uchf,0.19uaud,0.2usgd,4.62uthb,1.25usek,1.25unok,0.9udkk,2180.0uidr,7.6uphp,1.17uhkd"/g' ~/.terra/config/app.toml

# Extract and move the extract snapshot files to ~/.terra/data/

terrad start
```
Same error using these 3 versions
- `0.5.9` (from branch `v0.5.9`)
- `0.5.20` (from branch `v0.5.20`)
- `0.5.20-27-g4b2828bc` (from branch `public-node`, suggested by https://github.com/terra-money/classic-core/issues/762)

**Context & versions**
- terrad `0.5.9`, `0.5.20`, `0.5.20-27-g4b2828bc`
- go version go1.18.2 linux/amd64
- Ubuntu 20.04

**Comment by awsdataarchitect** [comment]
U r not using the branch public node. git checkout v0.5.9 won't work
